global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['localhost:8080']  # Configure your backend service address here

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] # Prometheus server itself